# Generated by Django 4.1.7 on 2023-02-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiation', '0002_patient_birthday_patient_dni_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
